#!/bin/sh
# FILE: "/disk01/home/joze/pub/gnuplot/gpconfopt"
# LAST MODIFICATION: "Fri Jan 21 13:11:52 2000 (joze)"
# (C) 1999 by Johannes Zellner, <johannes@zellner.org>
# $Id: gpconfopt,v 1.1 2000/02/11 18:41:37 lhecking Exp $

export CPPFLAGS=-I${HOME}/pub/gd1.3

./configure \
  --with-readline=gnu \
  --with-plot \
  --with-gd=${HOME}/pub/gd1.3/ \
  --with-png \
  --with-cwdrc \
  --enable-history-file \
  --enable-thin-splines \
  --enable-mouse "$@"
